### ISSUE TITLE
self.pdf_fonts should be renamed into self.fonts_used

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#114]
All PDF, Word and HTML layout naturally should utilize the same fonts.

This is from #108 .

**Comment by opoudjis** [comment]
CSA:
AzoSans, AzoSans-Light, SourceCodePro-Light

CalConnect:
SourceSansPro, SourceSerifPro, SourceCodePro, HanSans

IEC:
Arial, Times New Roman, HanSans, Courier

ISO:
Cambria, Times New Roman, Cambria Math, HanSans, Courier

ITU:
Arial, Courier, Times New Roman

OGC:
Arial, Courier, Times New Roman

Ribose:
SourceSansPro-Light, SourceSerifPro, SourceCodePro-Light, HanSans

UN:
Arial, Arial Black, Courier, Times New Roman, HanSans

**Comment by opoudjis** [comment]
The demand that the same fonts be used on PDF and DOC/HTML founders on the fact that different font decisions have been taken for the two; AzoSans-Light is being applied in PDF to footnotes and headers/footers, which is not a distinction made in DOC/HTML, nor will it be. I am extracting the relevant fonts to DOC/HTML, rather than reengineering all output to match PDF font usage.
