### ISSUE TITLE
Support ToC levels in xml

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma#226]
Add ToC levels value into metanorma xml (both presentation and semantic) to allowing non-static ToC levels generation in PDF (https://github.com/metanorma/mn-native-pdf/issues/337) and round-trip conversion from metanorma to STS (https://github.com/metanorma/mn-samples-bsi/issues/20
STS example:
```xml
<custom-meta>
	<meta-name>TOC Heading Level</meta-name>
	<meta-value>1</meta-value>
</custom-meta>
```
)

**Comment by opoudjis** [comment]
There is nothing whatsoever semantic about the number of ToC levels, and hardcoding number of ToC levels is a misfeature: we make a point of allowing Word and HTML to have different ToC levels, which is why ToC levels is an argument passed in to compilation. STS specifies TOC levels, but STS makes little real distinction between semantics and presentation. If the workflow requires presentation information to be embedded into Semantic XML, the workflow needs to be reconsidered.

...

That said, there is a top level `misc-container` element, between `bibdata` and `boilerplate`, that allows for random content. (That's where we store metric unit definitions in BIPM.) The STS custom-meta tag is a miscellanea element, and that's the appropriate place for it; it does not deserve formalisation in bibdata/ext, which is flavour-specific, and the content of custom-metadata is clearly open-ended: https://www.niso-sts.org/TagLibrary/niso-sts-TL-1-0-html/element/custom-meta.html

So, feel free to map custom-meta to misc-container:

````
<bibdata/>
<misc-container>
<metadata>
	<name>TOC Heading Level</name>
	<value>1</value>
</metadata>
</misc-container>
<boilerplate/>
````

And if that's ok with you, then I'll allow any `//misc-container/metadata[name = "TOC Heading Level"]/value` to override the configured use of `@htmltoclevels` and `@doctoclevels` when detected in Presentation XML.

**Comment by Intelligent2013** [comment]
@opoudjis may be `@htmltoclevels` and `@doctoclevels` or `@toclevels` in both presentation and semantic xml is enough?
There are two issues:
1. for OGC documents https://github.com/metanorma/metanorma-ogc/issues/328
I've tried to add `:toclevels: 3`,  but presentation xml doesn't contain `@htmltoclevels`, `@doctoclevels`, `@toclevels` (I've tried to generate presentation xml 3 weeks ago). Therefore I've asked you to add it into the presentation xml.

2. for round-trip conversion STS->MN ADOC->MN XML semantic ->STS. In principle, I can use `:toclevels:`, but it should be added into the semantic xml also.

**Comment by opoudjis** [comment]
Ugh.

OK: I'm adding these to misc-container, as: 

* //misc-container/presentation-metadata[name = "TOC Heading Levels"]/value
* //misc-container/presentation-metadata[name = "HTML TOC Heading Levels"]/value
* //misc-container/presentation-metadata[name = "DOC TOC Heading Levels"]/value

Putting "presentation-metadata" in, because who knows what else we need to put in there.

**Comment by Intelligent2013** [comment]
@opoudjis thanks!
