### ISSUE TITLE
All Ruby Windows GHA jobs failing because of bundler issue

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#261]
https://github.com/metanorma/metanorma/actions/runs/3218225972

**Comment by opoudjis** [comment]
Same issue today as yesterday:

https://github.com/metanorma/metanorma/actions/runs/3218225972/jobs/5273725733

GHA Windows agents take 40 minutes to install environment (15 mins on Nokogiri), and crash on attempt to install Expressir.

This is holding up fortnightly release.

**Comment by ronaldtse** [comment]
https://github.com/rubygems/rubygems/issues/5422 says this may be caused by a corrupt gemfile.lock, which is cached on github.

**Comment by ronaldtse** [comment]
The real issue is this: Bundler 2.3.23 fails on Windows with native gems:
* https://github.com/rubygems/rubygems/issues/5970

The only fix right now is to lock Bundler to 2.3.22, like this:
* https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/139

We have to apply this fix to all of the repositories, so @CAMOBAP can you please help mass apply this?

**Comment by opoudjis** [comment]
Note that this really is urgent: we are unable to release until this is dealt with, because metanorma-cli will not trigger docker otherwise.

**Comment by CAMOBAP** [comment]
Implemented and tested on https://github.com/metanorma/metanorma/actions/runs/3218225972

Waiting for https://github.com/metanorma/metanorma-cli/actions/runs/3218650484

**Comment by CAMOBAP** [comment]
Passed
