### ISSUE TITLE
Create a "canonical XML" output for XML compares

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#287]
The current XML comparison process relies a lot on whitespace fragility. For example, the specs at metanorma-plugin-lutaml is now broken because of:
1. In `<bibdata>`, there are no more whitespace newlines after tag closes.
2. The `<table>` whitespaces after its tags are different from before.

The [equivalent-xml gem](https://github.com/mbklein/equivalent-xml) does not help here (we already use it) because it does not know which tags are whitespace insensitive.

Specs should not be failing because of these changes, which are irrelevant to metanorma-plugin-* functionality.

We should create a "canonical XML format" where Metanorma XML content can be easily compared. It needs to do the following:
1. For all tags that represent textual nodes, their whitespaces should be kept
2. For all tags that do not represent textual nodes, the whitespaces in between should be a single newline.
3. For all tags that have internal orders that do not matter, sort those tags in alphabetical order

**Comment by opoudjis** [comment]
The intent of this issue is already resolved in the metanorma stack, with the xmlpp() method in spec/spec_helper.rb, which runs an XSLT stylesheet over output to manage whitespace consistently, and that is good enough. This task only involves applying that method to this gem, which I did not author and do not manage.

The detailed requirements you have on the other hand, of micro-differentiating text and non-text nodes, I will not do, and I will never do.
