### ISSUE TITLE
Fontist: support the attribute `:fonts:` for additional per-document fonts

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma#302]
Source issue: https://github.com/metanorma/pdfa-iso-32000-2/issues/4

Currently, `fontist` installs the fonts from the list determined in the metanorma gem, for instance (https://github.com/metanorma/metanorma-iso/blob/main/lib/metanorma/iso/processor.rb):
```ruby
      def fonts_manifest
        {
          "Cambria" => nil,
          "Cambria Math" => nil,
          "Times New Roman" => nil,
          "Source Han Sans" => nil,
          "Source Han Sans Normal" => nil,
          "Courier New" => nil,
        }
      end
```

Metanorma allows to set the additional font(s) in the document attribute `:fonts:`, for example:
```
:fonts: MS Gothic
```

Metanorma should pass these list to the `fontist` for the font installation/manifest generation.
Note: `fontist` doesn't have the entry for `MS Gothic` font installation, but for the pre-installed fonts (for instance, for Windows) it should return like this:
```
fontist install "MS Gothic"
Fonts found at:
- C:/Windows/Fonts/msgothic.ttc
```

**Comment by ronaldtse** [comment]
@opoudjis @CAMOBAP can you help discuss and check the best way we can implement this?

**Comment by opoudjis** [comment]
I have no idea what is happening, either because I didn't code it or because I never understood fontist, but:

* The document attribute `:fonts:` is being passed to isodoc as `@fontist_fonts` inside of isodoc, and as the option `:fonts` in the isodoc call.
* That attribute ends up processed in the metanorma gem, and its comma-delimited contents *are* installed by fontist.

The issue is rather that the attribute is not propagating from the header. Investigating.

**Comment by opoudjis** [comment]
Yes, timing issue: was initialising fonts before extracting options like :fonts: for processing, not after.
