### ISSUE TITLE
metanorma (or something along the pipeline) seems to turn a %20 part of a URL into %2520 in the output PDF

### ISSUE THREAD

**Issue by jerstlouis** [metanorma/metanorma#306]
With the following link:

https://maps.gnosis.earth/ogcapi/collections/sentinel2-l2a/map/tiles/GNOSISGlobalGrid/3/4/17?filter=SCL<8%20or%20SCL>10

([link](https://maps.gnosis.earth/ogcapi/collections/sentinel2-l2a/map/tiles/GNOSISGlobalGrid/3/4/17?filter=SCL<8%20or%20SCL>10))

in the output PDF this becomes:

https://maps.gnosis.earth/ogcapi/collections/sentinel2-l2a/map/tiles/GNOSISGlobalGrid/3/4/17?filter=SCL<8%2520or%2520SCL>10

([broken link](https://maps.gnosis.earth/ogcapi/collections/sentinel2-l2a/map/tiles/GNOSISGlobalGrid/3/4/17?filter=SCL<8%2520or%2520SCL>10))

**Comment by opoudjis** [comment]
Given what *Github* does to that link, as you can see for yourself in what you typed in as the ticket, you can see that the mixture of < and %20 is bad practice: you have a URL where part of the string is URL-encoded (%20) and part of it isn't (<). Browsers can cope with that (apparently); not all software can, demonstrably. I do recommend you publish the URL as the much less problematic https://maps.gnosis.earth/ogcapi/collections/sentinel2-l2a/map/tiles/GNOSISGlobalGrid/3/4/17?filter=SCL%3C8%20or%20SCL%3E10

I can confirm that the hyperlink with the < > in it is being XML-encoded (`&lt;` and `&#x3c;`), instead of URL-encoded, which is simply wrong, and is leading to the garbling that you report. I'll fix this, though I have to be clever about it...

**Comment by opoudjis** [comment]
````
https://maps.gnosis.earth/ogcapi/collections/sentinel2-l2a/map/tiles/GNOSISGlobalGrid/3/4/17?filter=SCL<8%20or%20SCL>10[test]

https://maps.gnosis.earth/ogcapi/collections/sentinel2-l2a/map/tiles/GNOSISGlobalGrid/3/4/17?filter=SCL%3C8%20or%20SCL%3E10[test]
````

will now both end up as:

`<link target="https://maps.gnosis.earth/ogcapi/collections/sentinel2-l2a/map/tiles/GNOSISGlobalGrid/3/4/17%3Ffilter%3DSCL%3C8%20or%20SCL%3E10">`

with the < > correctly escaped. And the PDF link ends up likewise as:

`https://maps.gnosis.earth/ogcapi/collections/sentinel2-l2a/map/tiles/GNOSISGlobalGrid/3/4/17?filter=SCL%3C8%20or%20SCL%3E10`

**Comment by opoudjis** [comment]
Need to deal with `username:password@` and `mailto:`

**Comment by opoudjis** [comment]
Using built in URI.parse(), which allows the URI with <>, but canonically outputs the URI (including the <>) URI-encoded. Writing my own URI parser is a fool's errand.
