### ISSUE TITLE
Implement Metanorma template repositories for supported SDOs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#53]
* [x] OGC (all done)
* [x] NIST (done for now)
* [x] CSD (mostly done -- check https://standards.calconnect.org/csd/cc-10001.html
* [x] ISO (only done for international-standard done, need to complete the other document types https://github.com/metanorma/mn-templates-iso/issues/2)
* [x] ITU
* [x] UN/ECE (recommendation and plenary)
* [x] IETF
* [ ] ~~GB~~ (no longer supported)
* [x] M3AAWG

**Comment by opoudjis** [comment]
I'm still only working for you 15 hrs a week.

**Comment by ronaldtse** [comment]
One day we need to complete these, so maybe we can get these done in May.

**Comment by opoudjis** [comment]
Manuel is working on these and I am reviewing, so removing myself.

**Comment by opoudjis** [comment]
Copying for @manuel489 from review https://github.com/metanorma/mn-templates-iso/pull/10:

Add here attributes from https://www.metanorma.com/author/ref/document-attributes/ which are important. I know you can't tell which ones are important, so I'll tell you: :-)

library-ics: ISO, IEC, GB
script: GB, UNECE, ITU (because they expect non-Latin)
revdate: all
iteration: all
keywords: ITU
html-uri, pdf-uri, doc-uri: OGC
published-date: all
implemented-date: GB
circulated-date: all
fullname, surname, initials, role, affiliation, address, contributor-uri, email: CSD, OGC

**Comment by ronaldtse** [comment]
https://github.com/metanorma/mn-templates-m3aawg now available. Closing.
