### ISSUE TITLE
Failed to load command metanorma

### ISSUE THREAD

**Issue by celic** [metanorma/metanorma#68]
Running the `Makefile` I end up with the following stack trace...

```
bundler: failed to load command: metanorma (/usr/local/bin/metanorma)
NoMethodError: undefined method `pass' for #<Asciidoctor::Rfc::V2::Converter:0x00007fc5a1493e50>
  /Library/Ruby/Gems/2.3.0/gems/metanorma-ietf-1.0.1/lib/asciidoctor/rfc/common/base.rb:15:in `convert'
  /Library/Ruby/Gems/2.3.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:75:in `convert'
  /Library/Ruby/Gems/2.3.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `block in content'
  /Library/Ruby/Gems/2.3.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `map'
  /Library/Ruby/Gems/2.3.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `content'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-ietf-1.0.1/lib/asciidoctor/rfc/v2/base.rb:247:in `block (2 levels) in section'
  /Library/Ruby/Gems/2.3.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:391:in `insert'
  /Library/Ruby/Gems/2.3.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:375:in `method_missing'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-ietf-1.0.1/lib/asciidoctor/rfc/v2/base.rb:246:in `block in section'
  /Library/Ruby/Gems/2.3.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:293:in `initialize'
  /Library/Ruby/Gems/2.3.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:254:in `new'
  /Library/Ruby/Gems/2.3.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/builder.rb:254:in `with'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-ietf-1.0.1/lib/asciidoctor/rfc/common/base.rb:355:in `noko'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-ietf-1.0.1/lib/asciidoctor/rfc/v2/base.rb:245:in `section'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-ietf-1.0.1/lib/asciidoctor/rfc/common/base.rb:15:in `convert'
  /Library/Ruby/Gems/2.3.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:75:in `convert'
  /Library/Ruby/Gems/2.3.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `block in content'
  /Library/Ruby/Gems/2.3.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `map'
  /Library/Ruby/Gems/2.3.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `content'
  /Library/Ruby/Gems/2.3.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1261:in `content'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-ietf-1.0.1/lib/asciidoctor/rfc/v2/base.rb:77:in `document'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-ietf-1.0.1/lib/asciidoctor/rfc/common/base.rb:15:in `convert'
  /Library/Ruby/Gems/2.3.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1190:in `convert'
  /Library/Ruby/Gems/2.3.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1521:in `convert'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-0.3.11/lib/metanorma/input/asciidoc.rb:8:in `process'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-ietf-1.0.1/lib/metanorma/ietf/processor.rb:33:in `input_to_isodoc'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-0.3.11/lib/metanorma/compile.rb:102:in `process_input'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-0.3.11/lib/metanorma/compile.rb:17:in `compile'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-cli-1.1.8/lib/metanorma/cli/compiler.rb:24:in `compile_file'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-cli-1.1.8/lib/metanorma/cli/compiler.rb:12:in `compile'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-cli-1.1.8/lib/metanorma/cli/compiler.rb:16:in `compile'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-cli-1.1.8/lib/metanorma/cli/command.rb:33:in `compile'
  /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-cli-1.1.8/lib/metanorma/cli.rb:56:in `start'
  /Library/Ruby/Gems/2.3.0/gems/metanorma-cli-1.1.8/exe/metanorma:14:in `<top (required)>'
  /usr/local/bin/metanorma:22:in `load'
  /usr/local/bin/metanorma:22:in `<top (required)>'
make: *** [draft-vassilev-acvp-drbg.html] Error 1
```

Could this be caused by the `adoc` I'm converting or could this be a bug in `metanorma`? I'm having a bit of trouble diagnosing this as it doesn't seem to point out an error in the `adoc` or `.tmp.xml`.

**Comment by ronaldtse** [comment]
@celic sorry for the delay in replying -- is this still an issue?

**Comment by opoudjis** [comment]
@celic, for bug reports in general, please provide the source Asciidoctor file, and details of how you're running this. Note also that we have been maintaining the Metanorma stack in Ruby 2.4 and 2.5 for the past few months, so the default Ruby installation you're using, 2.3, is running obsolete Metanorma code.

Now. The complaint in the code is that passthrough blocks are not being dealt with (`++++`).

As it turns out, in the RFC version of Asciidoctor (documented in https://www.metanorma.com/author/ietf/topics/markup/), passthroughts are restricted to being recognised *only* in the context of references (which are left natively in RFC XML). The code does not currently allow generic pass through of RFC XML (which is what this would do), and hence is refusing to process the document.

I can enable passthrough in the gem, but I'd like to understand what you're trying to achieve: this will be injecting native RFC XML in the middle of auto-converted RFC XML, and you would need to be very careful for it. If you're injecting source code, the `[source]` block is what you need instead.

**Comment by ronaldtse** [comment]
@celic if you can point out to the file that’s causing this error (if it is open source). 

The metanorma processor for RFC has a slight caveat — the references don’t work like the NIST version, because it was built using an older framework. We’re going to rectify this, but right now references in Metanorma RFC must be entered in XML pass through format. 

Here’s the minimal working template you can refer to if you prefer finding out the issue...

https://github.com/metanorma/rfc-asciirfc-minimal

Thanks!

**Comment by ronaldtse** [comment]
Oh, it’s the draft-vassilev-acvp-drbg document. We’ll check.

**Comment by ronaldtse** [comment]
Actually I couldn’t find it. There’s this one https://github.com/usnistgov/ACVP/blob/master/artifacts/acvp_sub_drbg.txt , but this might be a new source.

**Comment by ronaldtse** [comment]
If that’s the document, maybe the usage is for marking up the source JSON in the appendix. So the [source] block will do it.

**Comment by celic** [comment]
I don't have the metanorma docs on our GitHub yet. I have them saved internally. There are a lot of small files involved here, so I uploaded them to a personal fork of the original repository. https://github.com/celic/ACVP/blob/master/drbg has the adoc file along with the associated sections. the `common` directory might also be needed as a lot of sections come from there too.

**Comment by celic** [comment]
With the abundance of templates, I was missing a `[bibliography]` tag in my adoc. Putting that in fixed my issue.

**Comment by ronaldtse** [comment]
@celic wow, I was just trying to make things work over here: https://github.com/metanorma/ACVP/commit/0f3217dd02675d67d7161ccc2577ccd2f37bbd93

I've also converted the `[source]` and the `....` blocks, so feel free to cherry-pick it from our fork :wink:

And we found a bug in the process - https://github.com/metanorma/metanorma-ietf/issues/33
