### ISSUE TITLE
Metanorma should no longer require `:type` option when given file is Metanorma XML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#91]
Previously, when reading a Metanorma XML it is unclear which flavor it came from. In the newest Metanorma versions, the Metanorma XML namespaces indicate the document flavor used.

This means it is unnecessary now to specify the `:type` option to the following code.

https://github.com/metanorma/metanorma/blob/0d3c0ae02c2f220eb40aee1cab697011b6d1624f/lib/metanorma/compile.rb#L48-L52

This code should instead "detect" the Metanorma flavor used from the Metanorma XML directly (for older MN XML, show the same current warning).

How it should work:

Download and unzip [05-020r26.xml.zip](https://github.com/metanorma/metanorma/files/4178787/05-020r26.xml.zip).

Previously you need to run:
```sh
metanorma -t ogc 05-020r26.xml
```

If you run this:
```sh
metanorma 05-020r26.xml
```

This error will be shown:
```
[metanorma] Error: Please specify a standard type: [].
```

After this fix, the simpler command should work:
```sh
metanorma 05-020r26.xml
```

**Comment by opoudjis** [comment]
Nothing for me to do here. Note that this only applies when an XML file is the argument to metanorma; when an Asciidoc document is the argument, the type argument is used as before.

In all cases, the flavour is detected from the root tag. It is `{flavour}-standard` for all flavours, and `standard-document` for standoc.

**Comment by ronaldtse** [comment]
> when an Asciidoc document is the argument, the type argument is used as before

Not exactly true, the type argument can be specified within the Adoc file as an attribute. This means if the type is set in the adoc file, no command line arguments are necessary.

**Comment by opoudjis** [comment]
This is for XML > output parsing: make decision of which flavour to work with for rendering of Metanorma XML based on root element.

**Comment by opoudjis** [comment]
def compile_file
        Compile.new.compile(file, serialize_options)
      end

Metanorma::Compile is in metanorma/

**Comment by opoudjis** [comment]
I have a partial solution that works in rspec but not when run against a file.

I have updated the processors so that they register their root tags against the Metanorma registry. In order to work out what the flavour of an XML file is, get its root tag, and compare it against all the root tags recorded in the Metanorma registry: when a match is found, we know what the flavour is, and use that flavour as the type.

The catch is, Metanorma does not register the full list of flavour gems, so that we can iterate through all of them: metanorma-cli does. metanorma only loads in the one flavour we tell it to use as the flavour. Which means that this code does not work, and we do not want metanorma to invoke metanorma-cli, to retrieve the list of all gems (circular reference). Either the list of all gems should move from metanorma-cli to metanorma, so it is available within metanorma; or else the code I have added in metanorma, to detect the flavour of an XML document, should move to metanorma-cli, where all flavours are loaded in and the Metanorma registry can search through the root tags of all flavours.
